GET http://localhost:5000/api/auth

###

POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "luong sang",
    "password": "1232",
    "email": "luongtiensang1999@gmai.com",
    "gioitinh": "Nam",
    "diachi":"viakghwiu",
    "ngaysinh":"17/02/1999"
}


###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"luong sang",
    "password":"1232"
}

###
POST http://localhost:5000/api/book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZmU3NDRmMWRiNGViNjc5ZjMyNDYiLCJpYXQiOjE2MzYzNjc5OTZ9.uYEmHf3k1tJV-HXtoK5yrhwaiG-VrS3uSUcVTyEOFeI

{
    "tensach":"react",
    "tacgia":"react",
    "soluong": "1",
    "gia":"999",
    "mota": "sách bổ ích"
}

###
GET http://localhost:5000/api/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZTRjMzVkOGNmODEwYzUzMWZmZGIiLCJpYXQiOjE2MzYzNjMxMjF9.Z7QxRBEatVBNW883em7cMJmwTHxMb0wj8c8pa-64XuI

###
GET http://localhost:5000/api/book/6188f8e8a476363e52577888

####
GET http://localhost:5000/api/book/all/allbook


###
PUT http://localhost:5000/api/posts/6188f005bca7dc71684a98da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZTRjMzVkOGNmODEwYzUzMWZmZGIiLCJpYXQiOjE2MzYzNjMxMjF9.Z7QxRBEatVBNW883em7cMJmwTHxMb0wj8c8pa-64XuI

{
    "tensach":"truyện của tôi",
    "tacgia":"lung tung",
    "soluong": "1",
    "gia":"9999",
    "mota": "sách hay ơi là hay"
}

###
DELETE http://localhost:5000/api/posts/6188f005bca7dc71684a98da
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTg4ZTRjMzVkOGNmODEwYzUzMWZmZGIiLCJpYXQiOjE2MzYzNjMxMjF9.Z7QxRBEatVBNW883em7cMJmwTHxMb0wj8c8pa-64XuI

###
POST   http://localhost:5000/api/giohang
Content-Type: application/json


{
    "tensach": "abc",
    "tonggia": "1232",
    "soluong": "123"
}
